theme = "catppuccin_latte"

[editor]
scrolloff = 10
bufferline = "multiple"
jump-label-alphabet = "jfkdlsahgtyrueiwoqpbnvmcxz"
color-modes = true
auto-pairs = false
cursorline = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]

[keys.insert]
"C-f" = ":format"
"S-ret" = "@<ret><up><esc>o\t"
"q" = { "q" = "normal_mode" }

[keys.normal]
"H" = "extend_char_left"
"J" = "extend_line_up"
"K" = "extend_line_down"
"L" = "extend_char_right"
"C-/" = "toggle_comments"
"A-k" = ["select_mode", "goto_line_end","extend_line_below", "delete_selection", "move_line_up", "paste_before"]
"A-j" = ["select_mode", "goto_line_end","extend_line_below", "delete_selection", "paste_after"]
"V" = "keep_primary_selection"
";" = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.normal.space]
"t" = "@ b%id "
"C" = "no_op"

[keys.normal.space.c]
"c" = "@:sh count-slides <C-r>%<ret>"
# create a new slide with the same title as the header tag the cursor is currently in
"s" = "@ghf<gt>lt<lt>\"ty//section<ret>A<ret><ret><lt>section data-auto-animate<gt><ret><tab><lt>h2<gt><lt>/h2<gt><esc>Bt<gt>l\"tpA<ret><backspace><lt>/section<gt><esc>kA<ret>"
"y" = "@\"ty"
"p" = "@\"tp"
"e" = "@:pipe emmet-wrap \"<C-r>.\" "

[keys.select]
"A-k" = ["goto_line_end","extend_line_below",  "delete_selection", "move_line_up", "paste_before", "select_mode"]
"A-j" = ["goto_line_end","extend_line_below",  "delete_selection", "paste_after", "select_mode" ]
"Cmd-e" = {"w" = ":| tw \"%{selection}\""}
";" = ["collapse_selection", "keep_primary_selection", "normal_mode"]
