#!/bin/bash

# ===============
# getrel
# 
# Description: Automate download of RELION maps and masks.
# Usage:
# 	Set up ControlMaster and ControlPath in ~/.ssh/config
#   Create an alias to getrel for each host you run RELION on
#     E.g, alias gethost="getrel user@hostname /remote/dir/for/RELION/projects"
#   Locally, create a directory wherever you like which matches
#     the name of your RELION directory. That is, if your RELION
#     project is `/path/to/remote/project-dir`, maybe your local
#     directory could be `/local/path/to/project-dir`. The final
#     dirname is what has to match.
#   Run your alias in your loacl dir with just the job number to
#     download relevant result files from 3D Auto Refine,
#     3D Classification, and mask creation jobs. For example,
#     `gethost 12` to download maps from job 12.

if [ "$#" -ne 3 ]; then
    echo Usage:
    echo getrel {username}@{hostname} {scratch_dir} {job number}
    exit
fi

# set up variables
USERATHOST=$1
SC_DIR=$2
PROJECT=$(pwd | awk -F / '{print $NF}')
RELPATH=$2/$PROJECT
JOB_NUMBER=$3

# left-pad and add "job" to input, if job is given simply as a number
if ! grep -qs "job" $JOB_NUMBER
    then
    JOB_NUMBER=$(printf "%03d" $JOB_NUMBER)
    JOB_NUMBER=job$JOB_NUMBER
fi

# functions for each supported job type

get_refinement() {
    OUT_PATH=$PROJECT"_"map-$JOB_NUMBER.mrc

    scp $USERATHOST:$JOB_PATH/run_class001.mrc $OUT_PATH 2>/dev/null
}

get_three_class() {
    FINAL_ITER_COMM="ls $JOB_PATH/*.mrc | sed -nr 's/.*run_it([0-9]{3}).*/\1/p' | tail -n 1"

    FINAL_ITER=$(ssh $USERATHOST -t $FINAL_ITER_COMM 2>/dev/null | sed "s/\r//g")

    if [ -z $FINAL_ITER ]
        then
        echo Could not find 3D classification final iteration...
        exit
    else
        mkdir $PROJECT-3DC-$JOB_NUMBER
        pushd $PROJECT-3DC-$JOB_NUMBER
        MAPS_PATH=$JOB_PATH/run_it$FINAL_ITER"_"class*.mrc
        scp $USERATHOST:$MAPS_PATH .
		rename s/run/$PROJECT-$JOB_NUMBER/g *.mrc
        popd
    fi
}

get_mask() {
    OUT_PATH=$PROJECT"_"mask-$JOB_NUMBER.mrc

    scp $USERATHOST:$JOB_PATH/mask.mrc $OUT_PATH 2>/dev/null
}

get_postprocess() {
    OUT_PATH=$PROJECT"_"postprocess-$JOB_NUMBER.mrc
    scp $USERATHOST:$JOB_PATH/postprocess.mrc $OUT_PATH 2>/dev/null
}

# open the persistent SSH connection
ssh $USERATHOST &>/dev/null &

# job find string
JOB_FIND="find $RELPATH -mindepth 1 -maxdepth 2 -name $JOB_NUMBER"

# find the job
JOB_PATH=$(ssh $USERATHOST -t $JOB_FIND 2>/dev/null | sed 's/\r//g' | grep $JOB_NUMBER)

if grep Refine3D <<< $JOB_PATH
    then
    get_refinement 
elif grep Class3D <<< $JOB_PATH
    then
    get_three_class
elif grep MaskCreate <<< $JOB_PATH
    then
    get_mask
elif grep PostProcess <<< $JOB_PATH
    then
    get_postprocess
fi
