theme = "catppuccin_latte"

[editor]
scrolloff = 10
bufferline = "multiple"
jump-label-alphabet = "jfkdlsahgtyrueiwoqpbnvmcxz"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[keys.insert]
"C-f" = ":format"
"S-ret" = "@<ret><ret><up>\t\t"
"q" = { "q" = "normal_mode" }

[keys.normal]
"H" = "extend_char_left"
"J" = "extend_line_up"
"K" = "extend_line_down"
"L" = "extend_char_right"
";" = "flip_selections"
"A-;" = "collapse_selection"
"C-/" = "toggle_comments"
