[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 100           # set max completion results len for each group: words, snippets, unicode-input
feature_words = false                # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false        # enable "unicode input"
feature_paths = true                 # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)

# write logs to /tmp/completion.log
[language-server.scls.environment]
RUST_LOG = "info,simple-completion-language-server=info"
LOG_FILE = "/tmp/completion.log"

[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[[language]]
name = "html"
roots = [".git"]
language-servers = ["emmet-lsp", "scls", "codebook"]
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "python"
roots = [".git", "pyproject.toml"]
language-servers = ["jedi", "ruff", "scls"]
shebangs = ["python3", "python"]
file-types = ["py"]
