words = [
    "cryo",
    "ctf",
    "defocus",
    "denoised",
    "denoiser",
    "ldquo",
    "lowlight",
    "micrographs",
    "ndash",
    "rdquo",
    "revealjs",
    "srgb",
    "strikethrough",
    "structura",
    "unsplash",
]

ignore_patterns = [
    "(class|id)=\".+\"",
    "https?://[^\\s]+",
    "^[A-Z]{2,}$"
]
